extends: .eslintrc
rules:
  import/order: warn


  '@typescript-eslint/brace-style':
    - warn
    - stroustrup
  '@typescript-eslint/func-call-spacing': warn
  '@typescript-eslint/indent':
    - warn
    - tab
  '@typescript-eslint/member-delimiter-style':
    - warn
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
  '@typescript-eslint/no-extra-parens': warn
  '@typescript-eslint/no-extra-semi': warn
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/semi':
    - warn
    - never
  '@typescript-eslint/space-before-function-paren': warn
  array-element-newline:
    - warn
    - minItems: 3
  arrow-parens:
    - warn
    - as-needed
  capitalized-comments: warn
  comma-dangle:
    - warn
    - arrays: always-multiline
      exports: never
      functions: never
      imports: never
      objects: always-multiline
  curly:
    - warn
    - multi
  dot-location:
    - warn
    - property
  eol-last: warn
  function-paren-newline:
    - warn
    - consistent
  key-spacing: warn
  lines-around-comment: warn
  lines-between-class-members: warn
  multiline-comment-style: warn
  new-parens: warn
  newline-per-chained-call: warn
  no-multi-spaces: warn
  no-multiple-empty-lines: warn
  no-trailing-spaces:
    - warn
    - skipBlankLines: true
  no-useless-rename: warn
  object-curly-spacing: warn
  object-property-newline:
    - warn
    - allowAllPropertiesOnSameLine: true
  object-shorthand: warn
  padded-blocks: warn
  quote-props:
    - warn
    - as-needed
  space-before-blocks: warn
  space-before-function-paren: warn
  space-in-parens: warn
  space-infix-ops: warn
  spaced-comment: warn
  template-curly-spacing: warn
