version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    default_labels:
      - dependencies
    target_branch: dev

    allowed_updates:
      - match:
          update_type: all
          dependency_type: direct
      - match:
          update_type: security
          dependency_type: indirect

    update_schedule: weekly
    version_requirement_updates: increase_versions

    automerged_updates:
      - match:
          update_type: all
          dependency_type: all
