name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - dependencies
  pull_request:
    branches:
      - '*'

jobs:
  build:
    timeout-minutes: 6

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    services:

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: test_runner
          POSTGRES_PASSWORD: testtest
          POSTGRES_DB: graphql-boilerplate-test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: yarn install
      - name: start, generate schema and test with coverage
        run: yarn test:CI --token ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: test/coverage/lcov.info

        env:
          CI: true
